VIA_ENABLE = yes
VIAL_ENABLE = yes
ENCODER_MAP_ENABLE = yes
ENCODER_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = SSD1306

VIAL_INSECURE = no

EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = no
TAP_DANCE_ENABLE = yes

RGBLIGHT_ENABLE = yes

SWAP_HANDS_ENABLE = no
COMBO_ENABLE = no
GRAVE_ESC_ENABLE = yes
MAGIC_ENABLE = no
BOOTMAGIC_ENABLE = no
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
QMK_SETTINGS = no

KEY_OVERRIDE_ENABLE = no
LTO_ENABLE = yes
EXTRAFLAGS += -flto
