# Release some space
LTO_ENABLE = yes

# Vial Enable
VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = no

# Encoders Enable
ENCODER_MAP_ENABLE = yes
ENCODER_ENABLE = yes

# Screen Enable
OLED_ENABLE = yes
OLED_DRIVER = SSD1306

#Features
EXTRAKEY_ENABLE = yes # 500 bytes
TAP_DANCE_ENABLE = yes # 2000 bytes
RGBLIGHT_ENABLE = yes 
GRAVE_ESC_ENABLE = yes # 100 bytes

# Disabled Features
MOUSEKEY_ENABLE = no
SWAP_HANDS_ENABLE = no
COMBO_ENABLE = no
MAGIC_ENABLE = no
BOOTMAGIC_ENABLE = no
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
QMK_SETTINGS = no # 3000 bytes
KEY_OVERRIDE_ENABLE = no